### ISSUE TITLE
MUST UN-COMMENT API KEY BEFORE FINAL SUBMISSION

### ISSUE THREAD

**Issue by cjrhansen2** [Maniac-i/OSU-Bootcamp-Project-1#48]
We hit our pull request limit with the last API key, we made a new one and have commented it out to avoid hitting the limit again. We will uncomment it before submitting and presenting the final product (and try to not hit 500 pull requests again)

**Comment by Maniac-i** [comment]
wrapped up page layout and functionality and uncommented out the hotel api search
